name = "test-2341"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-2341_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-2341.wasm"
command = "npm run build:release"
